title: MultiGEC
author: 
  name: CompSLA group
  email: multigec@svenska.gu.se

description: > 
  A dataset for Multilingual Grammatical Error Correction

remote_theme: jekyll/minima

minima:
  skin: classic
  date_format: "%-d %B %Y"
  nav_pages:
    - data_format.md
    - stats.md
    - terms_of_use.md
    - contributors.md
    - publications.md
    - shared_task.md