title: MultiGEC
author: 
  name: CompSLA group

description: > 
  A dataset for Multilingual Grammatical Error Correction
header_pages:
  - terms_of_use.md
  - shared_task.md
  - publications.md

remote_theme: jekyll/minima

minima:
  skin: classic
  date_format: "%-d %B %Y"